progress:
  '#changed': 1682446335
  '#changed_by': '1'
  '#completed_items': 46
  '#items':
    install_and_enable_seo_checklist_module:
      '#completed': 1682433514
      '#uid': '1'
    install_and_enable_coffee_module:
      '#completed': 1682433721
      '#uid': '1'
    configure_coffee_module:
      '#completed': 1682433721
      '#uid': '1'
    install_and_enable_admin_toolbar_module:
      '#completed': 1682433514
      '#uid': '1'
    install_composer_command_line_tool:
      '#completed': 1682433721
      '#uid': '1'
    install_drush_command_line_tool:
      '#completed': 1682433721
      '#uid': '1'
    show_cli_commands:
      '#completed': 1682433721
      '#uid': '1'
    enable_clean_urls:
      '#completed': 1682434046
      '#uid': '1'
    install_and_enable_redirect_module:
      '#completed': 1682433514
      '#uid': '1'
    configure_the_redirect_module:
      '#completed': 1682434046
      '#uid': '1'
    install_and_enable_pathauto_module:
      '#completed': 1682433514
      '#uid': '1'
    configure_pathauto_module:
      '#completed': 1682434046
      '#uid': '1'
    create_pathauto_patterns:
      '#completed': 1682434046
      '#uid': '1'
    install_and_enable_file_field_paths_module:
      '#completed': 1682434046
      '#uid': '1'
    configure_file_field_paths_module:
      '#completed': 1682434046
      '#uid': '1'
    install_and_enable_metatag_module:
      '#completed': 1682435166
      '#uid': '1'
    install_and_enable_schema_metatag:
      '#completed': 1682435166
      '#uid': '1'
    set_metatags_for_your_site:
      '#completed': 1682435166
      '#uid': '1'
    install_and_enable_alternate_hreflang_module:
      '#completed': 1682435166
      '#uid': '1'
    install_and_enable_xml_sitemap_module:
      '#completed': 1682437022
      '#uid': '1'
    configure_xml_sitemap_module:
      '#completed': 1682437022
      '#uid': '1'
    install_and_enable_robotstxt_module:
      '#completed': 1682437022
      '#uid': '1'
    add_xml_sitemap_to_your_robotstxt_file:
      '#completed': 1682437022
      '#uid': '1'
    set_up_cron:
      '#completed': 1682437022
      '#uid': '1'
    google_accounts_sign_ups:
      '#completed': 1682444548
      '#uid': '1'
    install_and_enable_google_tag_manager_module:
      '#completed': 1682444548
      '#uid': '1'
    configure_google_tag_manager_module:
      '#completed': 1682444548
      '#uid': '1'
    submit_xml_sitemap_to_google:
      '#completed': 1682444548
      '#uid': '1'
    get_a_microsoft_account:
      '#completed': 1682444548
      '#uid': '1'
    authenticate_with_bing:
      '#completed': 1682444548
      '#uid': '1'
    submit_xml_sitemap_to_bing:
      '#completed': 1682444548
      '#uid': '1'
    install_and_enable_easy_breadcrumbs_module:
      '#completed': 1682446212
      '#uid': '1'
    configure_easy_breadcrumbs_module:
      '#completed': 1682446212
      '#uid': '1'
    install_and_enable_d8_editor_advanced_link_module:
      '#completed': 1682446212
      '#uid': '1'
    configure_text_formats_to_use_d8_editor_advanced_link_module:
      '#completed': 1682446212
      '#uid': '1'
    install_and_enable_sitemap_module:
      '#completed': 1682446212
      '#uid': '1'
    configure_sitemap_module:
      '#completed': 1682446212
      '#uid': '1'
    install_and_enable_search_404_module:
      '#completed': 1682446212
      '#uid': '1'
    configure_search_404_module:
      '#completed': 1682446212
      '#uid': '1'
    secure_your_website_with_https:
      '#completed': 1682446274
      '#uid': '1'
    move_to_fast_hosting:
      '#completed': 1682446274
      '#uid': '1'
    read_drupal_8_seo_by_ben_finklea:
      '#completed': 1682446335
      '#uid': '1'
    use_and_link_to_our_online_drupal_seo_guide:
      '#completed': 1682446335
      '#uid': '1'
    sign_up_for_a_drupal_org_account_if_you_dont_already_have_one:
      '#completed': 1682446335
      '#uid': '1'
    if_the_seo_checklist_module_helped_you_please_help_get_the_word_out:
      '#completed': 1682446335
      '#uid': '1'
    report_a_bug_or_recommend_changes_to_the_seo_checklist_module:
      '#completed': 1682446335
      '#uid': '1'
