progress:
  '#changed': 1682437022
  '#changed_by': '1'
  '#completed_items': 24
  '#items':
    install_and_enable_seo_checklist_module:
      '#completed': 1682433514
      '#uid': '1'
    install_and_enable_coffee_module:
      '#completed': 1682433721
      '#uid': '1'
    configure_coffee_module:
      '#completed': 1682433721
      '#uid': '1'
    install_and_enable_admin_toolbar_module:
      '#completed': 1682433514
      '#uid': '1'
    install_composer_command_line_tool:
      '#completed': 1682433721
      '#uid': '1'
    install_drush_command_line_tool:
      '#completed': 1682433721
      '#uid': '1'
    show_cli_commands:
      '#completed': 1682433721
      '#uid': '1'
    enable_clean_urls:
      '#completed': 1682434046
      '#uid': '1'
    install_and_enable_redirect_module:
      '#completed': 1682433514
      '#uid': '1'
    configure_the_redirect_module:
      '#completed': 1682434046
      '#uid': '1'
    install_and_enable_pathauto_module:
      '#completed': 1682433514
      '#uid': '1'
    configure_pathauto_module:
      '#completed': 1682434046
      '#uid': '1'
    create_pathauto_patterns:
      '#completed': 1682434046
      '#uid': '1'
    install_and_enable_file_field_paths_module:
      '#completed': 1682434046
      '#uid': '1'
    configure_file_field_paths_module:
      '#completed': 1682434046
      '#uid': '1'
    install_and_enable_metatag_module:
      '#completed': 1682435166
      '#uid': '1'
    install_and_enable_schema_metatag:
      '#completed': 1682435166
      '#uid': '1'
    set_metatags_for_your_site:
      '#completed': 1682435166
      '#uid': '1'
    install_and_enable_alternate_hreflang_module:
      '#completed': 1682435166
      '#uid': '1'
    install_and_enable_xml_sitemap_module:
      '#completed': 1682437022
      '#uid': '1'
    configure_xml_sitemap_module:
      '#completed': 1682437022
      '#uid': '1'
    install_and_enable_robotstxt_module:
      '#completed': 1682437022
      '#uid': '1'
    add_xml_sitemap_to_your_robotstxt_file:
      '#completed': 1682437022
      '#uid': '1'
    set_up_cron:
      '#completed': 1682437022
      '#uid': '1'
