_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  anonymous_login: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  comment: 0
  computed_field: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  current_page_crumb: 0
  custommap: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_token_value: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  libraries: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_token: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  profile: 0
  recaptcha: 0
  redirect: 0
  redirect_after_login: 0
  search: 0
  shortcut: 0
  simple_gmap: 0
  simple_popup_blocks: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_multidelete_terms: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_ui: 0
  webform: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable: 0
  classy: 0
  chartwell: 0
  gin: 0
profile: standard
