_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 84890d49-f817-463b-8d48-0e3400d24d0d
name: 'Chartwell Staffing'
mail: admin@chartwellstaff.com
slogan: ''
page:
  403: ''
  404: /search404
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
